version: '2'
services:
 web:
   build: .
   ports:
    - "80:80"
   depends_on:
    - db
   env_file:
    - .env
   volumes:
    - file-data:/data
 db:
   image: postgres:13-alpine
   ports:
    - "5432:5432"
   environment:
    - POSTGRES_PASSWORD=postgres
   volumes:
    - db-data:/var/lib/postgresql/data
volumes:
  file-data:
    driver: local
  db-data:
    driver: local
